### ISSUE TITLE
Implement `when` clause in main configuration for template for Jinja event plugin

### ISSUE THREAD

**Issue by rnv812** [eventum-project/eventum-plugins#5]
`when` option is intended to be used for filtering which templates are rendered **after picking** them using specified mode.

Suboptions to implement:

Logic:
- `or`
- `and`
- `not`

Checks:
- `in`
- `eq`
- `gt`
- `lt`
- `gte`
- `lte`

Examples usage:

```yml
templates:
  - logon:
      template: "logon_events.json.jinja"
      when:
        and:
          - in:
              tags: ["basic"]
          - in:
              locals.my_mapping: "some key"

```

**Comment by rnv812** [comment]
Final model of feature implementation

```yaml  
  mode: fsm
  
  templates:
    - normal:
        template_group:
          - "event_1.json.jinja"
          - "event_2.json.jinja"
        transition:
          to: suspicious
          when:
            in:
              locals.logged_on_users: "Hacker"
    - suspicious:
        template: "suspicious_event.json.jinja"
        transition:
          to: normal
          when:
            in:
              locals.logged_out_users: "Hacker"
```
